In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9277, 5337, 6858, 189],
 [9277, 5337, 6858, 5317],
 [9277, 9117, 6858, 3798],
 [9581, 8789, 5386, 4245, 1359],
 [9581, 8789, 5386, 4245, 6109],
 [9028, 9277, 4475, 6858, 9421],
 [6172, 1843, 1562, 4245]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9277 5337 6858  189]
 [   0    0    0    0 9277 5337 6858 5317]
 [   0    0    0    0 9277 9117 6858 3798]
 [   0    0    0 9581 8789 5386 4245 1359]
 [   0    0    0 9581 8789 5386 4245 6109]
 [   0    0    0 9028 9277 4475 6858 9421]
 [   0    0    0    0 6172 1843 1562 4245]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\SIDNOOR\Downloads\simple_rnn_imdb\quickenv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step


array([[[-1.02021545e-03,  9.76209715e-03, -6.00386411e-04,
         -4.49707769e-02, -3.13824043e-02, -3.83534543e-02,
         -6.74893707e-03,  3.52890752e-02, -2.10182797e-02,
         -1.28827244e-03],
        [-1.02021545e-03,  9.76209715e-03, -6.00386411e-04,
         -4.49707769e-02, -3.13824043e-02, -3.83534543e-02,
         -6.74893707e-03,  3.52890752e-02, -2.10182797e-02,
         -1.28827244e-03],
        [-1.02021545e-03,  9.76209715e-03, -6.00386411e-04,
         -4.49707769e-02, -3.13824043e-02, -3.83534543e-02,
         -6.74893707e-03,  3.52890752e-02, -2.10182797e-02,
         -1.28827244e-03],
        [-1.02021545e-03,  9.76209715e-03, -6.00386411e-04,
         -4.49707769e-02, -3.13824043e-02, -3.83534543e-02,
         -6.74893707e-03,  3.52890752e-02, -2.10182797e-02,
         -1.28827244e-03],
        [ 2.63471641e-02, -3.22971232e-02,  3.57811935e-02,
         -2.56867409e-02,  1.26319006e-03,  2.30658054e-03,
          4.27383222e-02,  1.42366029e-02, -3.128593

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9277, 5337, 6858,  189], dtype=int32)

In [15]:
import numpy as np

model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


array([[[-1.0202155e-03,  9.7620972e-03, -6.0038641e-04, -4.4970777e-02,
         -3.1382404e-02, -3.8353454e-02, -6.7489371e-03,  3.5289075e-02,
         -2.1018280e-02, -1.2882724e-03],
        [-1.0202155e-03,  9.7620972e-03, -6.0038641e-04, -4.4970777e-02,
         -3.1382404e-02, -3.8353454e-02, -6.7489371e-03,  3.5289075e-02,
         -2.1018280e-02, -1.2882724e-03],
        [-1.0202155e-03,  9.7620972e-03, -6.0038641e-04, -4.4970777e-02,
         -3.1382404e-02, -3.8353454e-02, -6.7489371e-03,  3.5289075e-02,
         -2.1018280e-02, -1.2882724e-03],
        [-1.0202155e-03,  9.7620972e-03, -6.0038641e-04, -4.4970777e-02,
         -3.1382404e-02, -3.8353454e-02, -6.7489371e-03,  3.5289075e-02,
         -2.1018280e-02, -1.2882724e-03],
        [ 2.6347164e-02, -3.2297123e-02,  3.5781194e-02, -2.5686741e-02,
          1.2631901e-03,  2.3065805e-03,  4.2738322e-02,  1.4236603e-02,
         -3.1285930e-02,  1.0758687e-02],
        [-2.0067608e-02, -3.6786310e-03,  2.6883055e-02, -3.